version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install --loglevel verbose
  pre_build:
    commands:
      - npm run test
  build:
    commands:
      - npm ci
      - npm run build

artifacts:
  files:
    - "**/*"
  name: "web-prod"
  base-directory: out

cache:
  paths:
    - /root/.npm/**/*
    - node_modules/**/*